baseURL = "https://lequoctrong.github.io/LeQuocTrong_Blog/"
languageCode = "vi-vn"
title = "Lê Quốc Trọng"
theme = "PaperMod"
publishDir = "docs"

[params]
    defaultTheme = "light"
    author = "Lê Quốc Trọng"
    description = "Portfolio và Blog chia sẻ kiến thức Lập trình mạng, Java Backend."

[params.assets]
    disableFingerprinting = true  # <--- DÒNG NÀY SẼ CỨU TRANG WEB CỦA BẠN KHỎI LỖI MẤT CSS

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Trang chủ"
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "Giới thiệu"
        url = "/about/"
        weight = 20
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts/"
        weight = 30
    [[menu.main]]
        identifier = "contact"
        name = "Liên hệ"
        url = "/contact/"
        weight = 40